language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cwhite5/docker-course -f Dockerfile.dev . 

script:
  - docker run -e CI=true cwhite5/docker-course npm run test